"""add stat_test to test_configs

Revision ID: 62216911bcf5
Revises: 80fac0484325
Create Date: 2026-08-04 01:51:46.938929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '62216911bcf5'
down_revision: Union[str, None] = '80fac0484325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'test_configs',
        sa.Column('stat_test', sa.String(length=16), nullable=False, server_default='Total'),
    )
    op.alter_column('test_configs', 'stat_test', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_configs', 'stat_test')
    # ### end Alembic commands ###
