"""add spend to test_configs and outcome_type to datasets

Revision ID: 80fac0484325
Revises: 13ffce6ff331
Create Date: 2026-08-03 17:57:49.718676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '80fac0484325'
down_revision: Union[str, None] = '13ffce6ff331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'datasets',
        sa.Column('outcome_type', sa.String(length=32), nullable=False, server_default='revenue'),
    )
    op.alter_column('datasets', 'outcome_type', server_default=None)
    op.add_column('test_configs', sa.Column('spend', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_configs', 'spend')
    op.drop_column('datasets', 'outcome_type')
    # ### end Alembic commands ###
