// Pre-renders the US map for the homepage: nation outline + state borders as static SVG paths
// (us-atlas states-albers-10m, already Albers-projected into a 975x610 viewBox) and a projected
// [x, y] for every DMA in the demo data, so the page needs no d3/topojson at runtime.
import { readFileSync, writeFileSync } from 'node:fs';
import { geoPath, geoAlbersUsa } from 'd3-geo';
import { feature, mesh } from 'topojson-client';

const us = JSON.parse(readFileSync('states-albers-10m.json', 'utf8'));
const round = (d) => d.replace(/(\d+\.\d)\d+/g, '$1');
const path = geoPath();
const nation = round(path(feature(us, us.objects.nation)));
const states = round(path(mesh(us, us.objects.states, (a, b) => a !== b)));
const proj = geoAlbersUsa().scale(1300).translate([487.5, 305]);

const norm = (s) => s.toLowerCase().replace(/,\s*[a-z]{2}(-[a-z]{2})*$/,'').replace(/\(.*?\)/g, '').replace(/&/g, 'and')
  .replace(/\bft\.?\b/g, 'fort').replace(/\bst\.?\b/g, 'saint').replace(/[^a-z]+/g, ' ').trim();
const dmaTopo = JSON.parse(readFileSync('nielsentopo.json', 'utf8')).objects.nielsen_dma.geometries.map((g) => g.properties);
const byNorm = new Map(dmaTopo.map((p) => [norm(p.dma1.replace(/,\s*[A-Z]{2}(-[A-Z]{2})*$/, '')), p]));
const firstWord = (s) => norm(s).split(' ')[0];

// Principal-city coordinates for names the boundary file spells differently or lacks.
const MANUAL = {
  'Washington, D.C. (Hagerstown)': [-77.04, 38.91], 'Boston (Manchester)': [-71.06, 42.36], 'Phoenix (Prescott)': [-112.07, 33.45],
  'Honolulu': [-157.86, 21.31], 'Anchorage': [-149.9, 61.22], 'Fairbanks': [-147.72, 64.84], 'Juneau': [-134.42, 58.3],
  'Portland, OR': [-122.68, 45.52], 'Portland-Auburn': [-70.26, 43.66], 'Austin, TX': [-97.74, 30.27],
  'Columbus, OH': [-82.99, 39.96], 'Columbus, GA': [-84.99, 32.46], 'Columbus-Tupelo-West Point-Starkville': [-88.43, 33.5],
  'Charleston, SC': [-79.93, 32.78], 'Charleston-Huntington': [-81.63, 38.35], 'Rochester, NY': [-77.61, 43.16],
  'Rochester-Mason City-Austin': [-92.47, 44.02], 'Jackson, MS': [-90.18, 32.3], 'Jackson, TN': [-88.81, 35.61],
  'Springfield, MO': [-93.29, 37.21], 'Springfield-Holyoke': [-72.59, 42.1], 'Lafayette, LA': [-92.02, 30.22],
  'Lafayette, IN': [-86.88, 40.42], 'Wilmington, NC': [-77.94, 34.23], 'Albany, GA': [-84.16, 31.58],
  'Albany-Schenectady-Troy': [-73.76, 42.65], 'Greenville-New Bern-Washington': [-77.37, 35.61],
  'Greenville-Spartanburg-Asheville-Anderson': [-82.4, 34.85], 'Greenwood-Greenville': [-90.18, 33.52],
  'Columbia, SC': [-81.03, 34.0], 'Columbia-Jefferson City': [-92.33, 38.95], 'Bend, OR': [-121.31, 44.06],
  'St. Louis': [-90.2, 38.63], 'St. Joseph': [-94.85, 39.77], 'Tri-Cities, TN-VA': [-82.35, 36.55],
  'Minneapolis-St. Paul': [-93.27, 44.98], 'Wichita-Hutchinson': [-97.34, 37.69], 'Wichita Falls-Lawton': [-98.49, 33.91], 'Tampa-St. Petersburg (Sarasota)': [-82.46, 27.95],
};
const lines = readFileSync('dma_ranks.txt', 'utf8').trim().split('\n').map((l) => l.split('|')[1].trim());
const dma = {}, how = { manual: 0, exact: 0, prefix: 0 }, missing = [];
for (const name of lines) {
  let ll = MANUAL[name];
  if (ll) how.manual++;
  else {
    const p = byNorm.get(norm(name));
    if (p) { ll = [p.longitude, p.latitude]; how.exact++; }
    else {
      const cands = dmaTopo.filter((q) => firstWord(q.dma1) === firstWord(name));
      if (cands.length === 1) { ll = [cands[0].longitude, cands[0].latitude]; how.prefix++; console.log('  prefix:', name, '=>', cands[0].dma1); }
    }
  }
  if (!ll) { missing.push(name); continue; }
  const xy = proj(ll);
  if (xy) dma[name] = [+xy[0].toFixed(1), +xy[1].toFixed(1)];
  else missing.push(name + ' (off-projection)');
}
writeFileSync('usmap.js', '/* Generated by build_map.mjs: US outline/state paths (975x610 Albers viewBox) and projected DMA points. */\n' +
  'window.US_MAP = ' + JSON.stringify({ viewBox: [975, 610], nation, states, dma }) + ';\n');
console.log('matched', Object.keys(dma).length, 'of', lines.length, JSON.stringify(how), 'missing:', missing.join(' | ') || 'none');
console.log('size KB', Math.round(readFileSync('usmap.js').length / 1024));
