/* Generated by convert.mjs from the Claude Design prototype. Do not edit by hand;
   change the prototype or convert.mjs and regenerate. */
window.REGIONS = {
  readout: (v, h) => `<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,380px),1fr))">
<div style="display:flex;flex-direction:column;gap:14px;padding:20px 16px;border-right:1px solid rgba(14,21,24,.12);min-width:0">
<div style="font:400 11px/1.4 'IBM Plex Mono',monospace;letter-spacing:.1em;text-transform:uppercase;color:#697478">Revenue, control → test</div>
<div id="bars-chart" style="display:flex;flex-direction:column;gap:14px;padding-top:6px">
<div style="display:grid;grid-template-columns:70px minmax(0,1fr);gap:12px;align-items:center"><span style="font:400 11px/1 'IBM Plex Mono',monospace;letter-spacing:.06em;text-transform:uppercase;color:#697478">Control</span><div style="position:relative;height:30px"><div style="position:absolute;left:0;top:0;bottom:0;width:${v.barsCtrlPct};background:#C9D0D3"></div><span style="position:absolute;left:${v.barsCtrlPct};top:50%;transform:translateY(-50%);margin-left:8px;font:400 12px/1 'IBM Plex Mono',monospace;color:#3B4448">${v.barsCtrlFmt}</span></div></div>
<div style="display:grid;grid-template-columns:70px minmax(0,1fr);gap:12px;align-items:center"><span style="font:400 11px/1 'IBM Plex Mono',monospace;letter-spacing:.06em;text-transform:uppercase;color:#0E1518">Test</span><div style="position:relative;height:30px"><div style="position:absolute;left:0;top:0;bottom:0;width:${v.barsCtrlPct};background:#0E1518"></div><div style="position:absolute;top:0;bottom:0;left:${v.barsCtrlPct};width:${v.barsLiftPct};background:#0E7490"></div><span style="position:absolute;left:${v.barsTestPct};top:50%;transform:translateY(-50%);margin-left:8px;font:400 12px/1 'IBM Plex Mono',monospace;color:#0E1518;white-space:nowrap">${v.barsTestFmt}</span></div></div>
<div style="display:grid;grid-template-columns:70px minmax(0,1fr);gap:12px"><span></span><div style="position:relative;height:18px"><div style="position:absolute;top:0;height:8px;left:${v.barsCtrlPct};width:${v.barsLiftPct};border:1px solid #0E7490;border-top:0"></div><span style="position:absolute;top:10px;left:${v.barsCtrlPct};font:400 11px/1.2 'IBM Plex Mono',monospace;color:#0E7490;white-space:nowrap;transform:translateX(-30%)">Lift ${v.barsLiftFmt}</span></div></div>
</div>
</div>
<div style="display:flex;flex-direction:column;gap:12px;padding:20px 16px;min-width:0">
<div style="display:flex;flex-wrap:wrap;justify-content:space-between;gap:6px 16px;font:400 11px/1.4 'IBM Plex Mono',monospace;letter-spacing:.1em;text-transform:uppercase;color:#697478"><span>Cumulative revenue</span><span style="display:flex;align-items:center;gap:12px"><span style="display:flex;align-items:center;gap:6px"><i style="width:14px;height:2px;background:#0E1518"></i>Test</span><span style="display:flex;align-items:center;gap:6px"><i style="width:14px;height:0;border-top:1.5px dashed #697478"></i>Control</span></span></div>
<div id="cum-chart" style="position:relative;height:170px;border-bottom:1px solid rgba(14,21,24,.35)">
<svg viewBox="0 0 1000 200" preserveAspectRatio="none" style="position:absolute;inset:0;width:100%;height:100%;overflow:visible">
<path d="${v.cumLiftArea}" fill="rgba(14,116,144,.14)"></path>
<path d="${v.cumCtrlPath}" fill="none" stroke="#697478" stroke-width="1.5" stroke-dasharray="5 4" vector-effect="non-scaling-stroke"></path>
<path d="${v.cumTestPath}" fill="none" stroke="#0E1518" stroke-width="2" vector-effect="non-scaling-stroke"></path>
</svg>
</div>
<div style="display:flex;justify-content:space-between;font:400 10px/1 'IBM Plex Mono',monospace;color:#697478"><span>Day 1</span><span>Day 45</span></div>
</div>
</div>
</div>`,
  design: (v, h) => `${v.tabsOn ? `
<div role="tablist" aria-label="Design details" style="display:flex;border-bottom:1px solid rgba(14,21,24,.2);overflow-x:auto;background:#FAFBFC">
${(v.tabs || []).map((t) => `
<button role="tab" aria-selected="${t.active}" data-on-click="${h(t.select)}" style="flex:1;min-height:44px;padding:0 14px;background:none;border:0;border-bottom:2px solid ${t.line};margin-bottom:-1px;cursor:pointer;font:400 11px/1 'IBM Plex Mono',monospace;letter-spacing:.1em;text-transform:uppercase;color:${t.color};white-space:nowrap">${t.label}</button>
`).join('')}
</div>
` : ''}

<div style="display:${v.marketsDisplay};grid-template-columns:repeat(auto-fit,minmax(min(100%,340px),1fr));border-bottom:1px solid rgba(14,21,24,.2)">
<div style="grid-column:span 2;display:flex;flex-direction:column;gap:12px;padding:20px 16px;border-right:1px solid rgba(14,21,24,.12);min-width:0">
<div style="display:flex;flex-wrap:wrap;justify-content:space-between;gap:8px 16px;font:400 11px/1.4 'IBM Plex Mono',monospace;letter-spacing:.1em;text-transform:uppercase;color:#697478">
<span>Where the test runs</span>
<span style="display:flex;flex-wrap:wrap;gap:6px 16px">
<span style="display:flex;align-items:center;gap:6px"><span style="width:10px;height:10px;border-radius:50%;background:#0E1518"></span>Test · sized by revenue</span>
<span style="display:flex;align-items:center;gap:6px"><span style="width:10px;height:10px;border-radius:50%;border:1.5px solid #0E7490"></span>Control · sized by weight</span>
</span>
</div>
<div id="market-map" style="position:relative;width:100%;aspect-ratio:975/610">
<svg viewBox="0 0 975 610" style="position:absolute;inset:0;width:100%;height:100%" role="img" aria-label="US map: test markets filled, control markets outlined">
<path d="${v.mapNation}" fill="#EFF2F3" stroke="none"></path>
<path d="${v.mapStates}" fill="none" stroke="rgba(14,21,24,.18)" stroke-width="0.8" stroke-linejoin="round"></path>
${(v.mapControl || []).map((p) => `
<circle cx="${p.x}" cy="${p.y}" r="${p.r}" fill="${p.fill}" stroke="#0E7490" stroke-width="${p.sw}" data-on-mouseenter="${h(p.enter)}" data-on-mouseleave="${h(v.clearHover)}" style="cursor:default"></circle>
`).join('')}
${(v.mapTest || []).map((p) => `
<circle cx="${p.x}" cy="${p.y}" r="${p.r}" fill="#0E1518" stroke="${p.stroke}" stroke-width="3" data-on-mouseenter="${h(p.enter)}" data-on-mouseleave="${h(v.clearHover)}" style="cursor:default"></circle>
`).join('')}
</svg>
${v.mapLoading ? `<span style="position:absolute;inset:0;display:flex;align-items:center;justify-content:center;font:400 11px/1 'IBM Plex Mono',monospace;letter-spacing:.1em;text-transform:uppercase;color:#697478">Loading map…</span>` : ''}
</div>
<div style="display:flex;justify-content:space-between;gap:12px;min-height:20px;padding-top:10px;border-top:1px solid rgba(14,21,24,.12);font:400 12px/1.5 'IBM Plex Mono',monospace;color:#3B4448">
<span>${v.hoverLabel}</span><span style="color:#697478">${v.hoverMeta}</span>
</div>
</div>
<div style="display:flex;flex-direction:column;gap:22px;padding:20px 16px;min-width:0">
<div style="display:flex;flex-direction:column;gap:10px">
<span style="font:400 11px/1.4 'IBM Plex Mono',monospace;letter-spacing:.12em;text-transform:uppercase;color:#697478">Test markets · share of revenue</span>
<ul id="market-list" style="list-style:none;margin:0;padding:0;border-top:1px solid rgba(14,21,24,.28)">
${(v.marketList || []).map((m) => `
<li data-on-mouseenter="${h(m.enter)}" data-on-mouseleave="${h(v.clearHover)}" style="display:grid;grid-template-columns:minmax(0,1fr) 44px 42px;align-items:center;gap:10px;padding:6px 0;border-bottom:1px solid rgba(14,21,24,.1);font:400 13px/1.3 'IBM Plex Sans',sans-serif;color:#0E1518;background:${m.bg}"><span style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${m.name}</span><span style="height:6px;background:rgba(14,21,24,.08);position:relative"><span style="position:absolute;left:0;top:0;bottom:0;width:${m.bar};background:#0E1518"></span></span><span style="text-align:right;font:400 12px/1 'IBM Plex Mono',monospace;color:#3B4448">${m.pct}</span></li>
`).join('')}
</ul>
</div>
<div style="display:flex;flex-direction:column;gap:10px">
<span style="font:400 11px/1.4 'IBM Plex Mono',monospace;letter-spacing:.12em;text-transform:uppercase;color:#697478">Control built from · weight</span>
<ul id="donor-list" style="list-style:none;margin:0;padding:0;border-top:1px solid rgba(14,21,24,.28)">
${(v.donorList || []).map((m) => `
<li data-on-mouseenter="${h(m.enter)}" data-on-mouseleave="${h(v.clearHover)}" style="display:grid;grid-template-columns:minmax(0,1fr) 44px 42px;align-items:center;gap:10px;padding:6px 0;border-bottom:1px solid rgba(14,21,24,.1);font:400 13px/1.3 'IBM Plex Sans',sans-serif;color:#0E1518;background:${m.bg}"><span style="overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${m.name}</span><span style="height:6px;background:rgba(14,21,24,.08);position:relative"><span style="position:absolute;left:0;top:0;bottom:0;width:${m.bar};border:1px solid #0E7490;background:rgba(14,116,144,.15)"></span></span><span style="text-align:right;font:400 12px/1 'IBM Plex Mono',monospace;color:#3B4448">${m.pct}</span></li>
`).join('')}
</ul>
<p data-k="design.donor_note" style="font:400 12px/1.5 'IBM Plex Mono',monospace;color:#697478">Top 5 of 27 markets in the weighted control.</p>
</div>
</div>
</div>

<div style="display:${v.fitPowerDisplay};grid-template-columns:repeat(auto-fit,minmax(min(100%,380px),1fr));border-bottom:1px solid rgba(14,21,24,.2)">
<div style="display:${v.fitDisplay};flex-direction:column;gap:12px;padding:20px 16px;border-right:1px solid rgba(14,21,24,.12);min-width:0">
<div style="display:flex;flex-wrap:wrap;justify-content:space-between;gap:6px 16px;font:400 11px/1.4 'IBM Plex Mono',monospace;letter-spacing:.1em;text-transform:uppercase;color:#697478"><span>Test markets vs. modeled control, before launch</span><span style="display:flex;align-items:center;gap:12px"><span style="display:flex;align-items:center;gap:6px"><i style="width:14px;height:2px;background:#0E1518"></i>Test</span><span style="display:flex;align-items:center;gap:6px"><i style="width:14px;height:2px;background:#9AA3A7"></i>Control</span></span></div>
<div id="fit-chart" style="position:relative;height:180px;border-bottom:1px solid rgba(14,21,24,.35)">
<svg viewBox="0 0 1000 200" preserveAspectRatio="none" style="position:absolute;inset:0;width:100%;height:100%;overflow:visible">
<line x1="0" x2="1000" y1="50" y2="50" stroke="rgba(14,21,24,.08)" vector-effect="non-scaling-stroke"></line>
<line x1="0" x2="1000" y1="100" y2="100" stroke="rgba(14,21,24,.08)" vector-effect="non-scaling-stroke"></line>
<line x1="0" x2="1000" y1="150" y2="150" stroke="rgba(14,21,24,.08)" vector-effect="non-scaling-stroke"></line>
<path d="${v.fitCtrlPath}" fill="none" stroke="#9AA3A7" stroke-width="1.5" vector-effect="non-scaling-stroke"></path>
<path d="${v.fitTestPath}" fill="none" stroke="#0E1518" stroke-width="1.5" vector-effect="non-scaling-stroke"></path>
</svg>
</div>
<div style="display:flex;justify-content:space-between;font:400 10px/1 'IBM Plex Mono',monospace;color:#697478"><span>${v.fitFirst}</span><span>${v.fitMid}</span><span>${v.fitLast} · launch →</span></div>
<p data-k="design.fit_note" style="font:400 12px/1.5 'IBM Plex Mono',monospace;color:#697478">Last 120 days before launch. Average daily gap between test and control: 3.1%.</p>
</div>
<div style="display:${v.powerDisplay};flex-direction:column;gap:12px;padding:20px 16px;min-width:0">
<div style="font:400 11px/1.4 'IBM Plex Mono',monospace;letter-spacing:.1em;text-transform:uppercase;color:#697478">Chance of detecting a lift of each size</div>
<div style="display:grid;grid-template-columns:34px minmax(0,1fr);gap:6px">
<div style="position:relative;height:180px;font:400 10px/1 'IBM Plex Mono',monospace;color:#697478"><span style="position:absolute;right:0;top:0;transform:translateY(-50%)">100%</span><span style="position:absolute;right:0;top:20%;transform:translateY(-50%)">80%</span><span style="position:absolute;right:0;top:100%;transform:translateY(-50%)">0%</span></div>
<div id="power-chart" style="position:relative;height:180px;border-bottom:1px solid rgba(14,21,24,.35);border-left:1px solid rgba(14,21,24,.35)">
<svg viewBox="0 0 1000 200" preserveAspectRatio="none" style="position:absolute;inset:0;width:100%;height:100%;overflow:visible">
<line x1="0" x2="1000" y1="40" y2="40" stroke="#697478" stroke-dasharray="4 4" vector-effect="non-scaling-stroke"></line>
<path d="${v.powerArea}" fill="rgba(14,116,144,.1)"></path>
<path d="${v.powerPath}" fill="none" stroke="#0E7490" stroke-width="2" vector-effect="non-scaling-stroke"></path>
</svg>
<span style="position:absolute;left:${v.powerMdeLeft};top:${v.powerMdeTop};width:10px;height:10px;margin:-5px 0 0 -5px;border-radius:50%;background:#0E7490;border:2px solid #FFFFFF;box-sizing:content-box"></span>
<span style="position:absolute;left:${v.powerMdeLeft};top:${v.powerMdeTop};margin:12px 0 0 10px;font:400 11px/1.3 'IBM Plex Mono',monospace;color:#0E7490;white-space:nowrap">${v.powerMdeLabel}</span>
</div>
<div></div>
<div style="position:relative;height:12px;font:400 10px/1 'IBM Plex Mono',monospace;color:#697478"><span style="position:absolute;left:0">0%</span><span style="position:absolute;left:25%;transform:translateX(-50%)">5%</span><span style="position:absolute;left:50%;transform:translateX(-50%)">10%</span><span style="position:absolute;left:75%;transform:translateX(-50%)">15%</span><span style="position:absolute;right:0">20% lift</span></div>
</div>
<p style="font:400 12px/1.5 'IBM Plex Mono',monospace;color:#697478">Simulated by planting each lift in past periods and checking whether the test finds it.</p>
</div>
</div>

<div style="display:${v.checksDisplay};grid-template-columns:repeat(auto-fit,minmax(min(100%,340px),1fr))">
<div style="grid-column:span 2;display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,260px),1fr));gap:18px clamp(18px,3vw,40px);align-items:center;padding:22px 16px;border-right:1px solid rgba(14,21,24,.12);min-width:0">
<div style="display:flex;flex-direction:column;gap:10px">
<span style="font:400 11px/1.4 'IBM Plex Mono',monospace;letter-spacing:.12em;text-transform:uppercase;color:#697478">Can this test see a result that matters?</span>
<p style="font:400 15px/1.6 'IBM Plex Sans',sans-serif;color:#3B4448;max-width:46ch">Any true cost per incremental order below <strong data-k="design.max_cpa_fmt" style="font-weight:500;color:#0E1518">$169</strong> will show up as significant. Break-even at this brand's average order value is <strong data-k="design.breakeven_cpa_fmt" style="font-weight:500;color:#0E1518">$92</strong>, so the test has <strong data-k="design.headroom_fmt" style="font-weight:500;color:#0E1518">1.8x</strong> headroom.</p>
</div>
<div style="display:flex;flex-direction:column;gap:8px;min-width:0">
<div id="sens-chart" style="position:relative;height:64px">
<div style="position:absolute;left:0;right:0;top:26px;height:14px;background:rgba(14,21,24,.05)"></div>
<div style="position:absolute;left:0;top:26px;height:14px;width:${v.sensMaxPct};background:rgba(14,116,144,.16);border-right:2px solid #0E7490"></div>
<div style="position:absolute;top:18px;height:30px;width:0;border-left:1.5px dashed #0E1518;left:${v.sensBePct}"></div>
<span style="position:absolute;top:0;left:${v.sensBePct};transform:translateX(-50%);font:400 10.5px/1.2 'IBM Plex Mono',monospace;color:#0E1518;white-space:nowrap">Break-even ${v.sensBeFmt}</span>
<span style="position:absolute;top:50px;left:${v.sensMaxPct};transform:translateX(-100%);font:400 10.5px/1.2 'IBM Plex Mono',monospace;color:#0E7490;white-space:nowrap">Detectable up to ${v.sensMaxFmt}</span>
</div>
<div style="position:relative;height:12px;font:400 10px/1 'IBM Plex Mono',monospace;color:#697478;border-top:1px solid rgba(14,21,24,.28);padding-top:4px"><span style="position:absolute;left:0;top:5px">$0</span><span style="position:absolute;left:40%;top:5px;transform:translateX(-50%)">$100</span><span style="position:absolute;left:80%;top:5px;transform:translateX(-50%)">$200</span><span style="position:absolute;right:0;top:5px">$250</span></div>
<span style="font:400 10px/1.3 'IBM Plex Mono',monospace;letter-spacing:.06em;text-transform:uppercase;color:#697478;padding-top:6px">Cost per incremental order</span>
</div>
</div>
<div style="display:flex;flex-direction:column;gap:10px;padding:22px 16px;border-top:1px solid rgba(14,21,24,.12);margin-top:-1px">
<span style="font:400 11px/1.4 'IBM Plex Mono',monospace;letter-spacing:.12em;text-transform:uppercase;color:#697478">Placebo check</span>
<p style="display:flex;align-items:center;gap:10px;font:500 20px/1.2 Archivo,Helvetica,sans-serif;color:#0E1518"><span style="width:9px;height:9px;background:#0E7490"></span><span data-k="design.placebo_verdict">Passed</span></p>
<p data-k="design.placebo_note" style="font:400 12px/1.5 'IBM Plex Mono',monospace;color:#3B4448">No false lift in 5 past 45-day windows (largest: 1.9%).</p>
<p style="font:400 12px/1.5 'IBM Plex Mono',monospace;color:#697478">We rerun the design on past periods where nothing happened. If it "finds" a lift there, the markets get changed before launch.</p>
</div>
</div>`,
  gap: (v, h) => `<figure id="gap-chart" aria-label="Platform-reported ROAS compared with measured incremental ROAS" style="margin:0;display:flex;flex-direction:column;gap:26px;padding:clamp(20px,2.6vw,32px);border:1px solid rgba(14,21,24,.2);background:#FAFBFC">
<div style="display:flex;flex-direction:column;gap:10px">
<div style="display:flex;justify-content:space-between;align-items:baseline;gap:12px"><span style="font:400 11px/1.4 'IBM Plex Mono',monospace;letter-spacing:.12em;text-transform:uppercase;color:#697478">Platform-reported ROAS</span><span data-k="readout.reported_roas_fmt" style="font:500 28px/1 Archivo,Helvetica,sans-serif;color:#0E1518;font-variant-numeric:tabular-nums">3.4x</span></div>
<div style="position:relative;height:34px;background:rgba(14,21,24,.05)"><div style="position:absolute;left:0;top:0;bottom:0;width:${v.gapRepPct};background:#F97316"></div></div>
<span style="font:400 12px/1.4 'IBM Plex Sans',sans-serif;color:#556065">Credit the ad platform gives itself. Taken on trust.</span>
</div>
<div style="display:flex;flex-direction:column;gap:10px">
<div style="display:flex;justify-content:space-between;align-items:baseline;gap:12px"><span style="font:400 11px/1.4 'IBM Plex Mono',monospace;letter-spacing:.12em;text-transform:uppercase;color:#697478">Measured incremental ROAS</span><span data-k="readout.roi_fmt" style="font:500 28px/1 Archivo,Helvetica,sans-serif;color:#0E1518;font-variant-numeric:tabular-nums">1.20x</span></div>
<div style="position:relative;height:34px;background:rgba(14,21,24,.05)">
<div style="position:absolute;left:0;top:0;bottom:0;width:${v.gapRoiPct};background:#0E1518"></div>
<div style="position:absolute;top:50%;height:1px;background:#0E1518;left:${v.gapCiLeft};width:${v.gapCiWidth}"></div>
<div style="position:absolute;top:9px;height:16px;width:1px;background:#0E1518;left:${v.gapCiLeft}"></div>
<div style="position:absolute;top:9px;height:16px;width:1px;background:#0E1518;left:${v.gapCiRight}"></div>
</div>
<span style="font:400 12px/1.4 'IBM Plex Sans',sans-serif;color:#556065">What the holdout showed, with its <span data-k="readout.roi_ci_fmt">90% CI 0.56x–1.83x</span>.</span>
</div>
<div style="position:relative;height:14px;border-top:1px solid rgba(14,21,24,.28);font:400 10px/1 'IBM Plex Mono',monospace;color:#697478">
<span style="position:absolute;left:0;top:6px">0x</span><span style="position:absolute;left:25%;top:6px;transform:translateX(-50%)">1x</span><span style="position:absolute;left:50%;top:6px;transform:translateX(-50%)">2x</span><span style="position:absolute;left:75%;top:6px;transform:translateX(-50%)">3x</span><span style="position:absolute;right:0;top:6px">4x</span>
</div>
</figure>`,
  hero: (v, h) => `<figure aria-label="Illustrative test readout: platform-reported revenue compared with measured revenue against a holdout control" style="margin:0;border:1px solid rgba(239,242,243,.18);background:#0A1013;display:flex;flex-direction:column;min-width:0">
<div style="display:flex;align-items:center;justify-content:space-between;gap:12px;padding:11px 16px;border-bottom:1px solid rgba(239,242,243,.16);font:400 11px/1.4 'IBM Plex Mono',monospace;letter-spacing:.12em;text-transform:uppercase;color:rgba(239,242,243,.7)">
<span style="display:flex;align-items:center;gap:10px"><span style="width:7px;height:7px;border-radius:50%;background:#EFF2F3"></span>Live read — CTV test</span>
<span style="font:400 10px/1 'IBM Plex Mono',monospace;letter-spacing:.1em;padding:4px 8px;border:1px solid rgba(239,242,243,.3);color:rgba(239,242,243,.7)">Illustrative</span>
</div>
<div style="display:flex;flex-direction:column;gap:8px;padding:14px 16px 0">
<div style="display:flex;align-items:baseline;justify-content:space-between;gap:12px;font:400 11px/1.4 'IBM Plex Mono',monospace;letter-spacing:.1em;text-transform:uppercase;color:rgba(239,242,243,.7)">
<span>Day <span style="color:#EFF2F3;font-variant-numeric:tabular-nums">${v.heroDayStr}</span> of 45</span>
<span>${v.heroPhase}</span>
</div>
<div style="display:flex;gap:2px;height:8px">
${(v.heroTicks || []).map((t) => `<span style="flex:1;background:${t.bg}"></span>`).join('')}
</div>
</div>
<div id="hero-chart" style="position:relative;height:clamp(200px,24vw,260px);margin:18px 16px 0;border-bottom:1px solid rgba(239,242,243,.3)">
<svg viewBox="0 0 1000 300" preserveAspectRatio="none" style="position:absolute;inset:0;width:100%;height:100%;overflow:visible">
<line x1="0" x2="1000" y1="75" y2="75" stroke="rgba(239,242,243,.08)" vector-effect="non-scaling-stroke"></line>
<line x1="0" x2="1000" y1="150" y2="150" stroke="rgba(239,242,243,.08)" vector-effect="non-scaling-stroke"></line>
<line x1="0" x2="1000" y1="225" y2="225" stroke="rgba(239,242,243,.08)" vector-effect="non-scaling-stroke"></line>
<path d="${v.heroLiftArea}" fill="rgba(239,242,243,.13)"></path>
<path d="${v.heroControlPath}" fill="none" stroke="rgba(239,242,243,.6)" stroke-width="1.5" stroke-dasharray="5 4" vector-effect="non-scaling-stroke"></path>
<path d="${v.heroTestPath}" fill="none" stroke="#EFF2F3" stroke-width="2" vector-effect="non-scaling-stroke"></path>
<path d="${v.heroRepPath}" fill="none" stroke="#F97316" stroke-width="2" vector-effect="non-scaling-stroke"></path>
<line x1="${v.heroCursorX}" x2="${v.heroCursorX}" y1="0" y2="300" stroke="rgba(239,242,243,.25)" vector-effect="non-scaling-stroke"></line>
</svg>
<span style="position:absolute;left:${v.heroCursorPct};top:${v.heroRepTop};width:9px;height:9px;margin:-4.5px 0 0 -4.5px;border-radius:50%;background:#F97316"></span>
<span style="position:absolute;left:${v.heroCursorPct};top:${v.heroTestTop};width:9px;height:9px;margin:-4.5px 0 0 -4.5px;border-radius:50%;background:#EFF2F3"></span>
<span style="position:absolute;left:${v.heroCursorPct};top:${v.heroCtrlTop};width:9px;height:9px;margin:-4.5px 0 0 -4.5px;border-radius:50%;background:#0A1013;border:1.5px solid rgba(239,242,243,.7)"></span>
${v.heroShowNotes ? `
<span style="position:absolute;right:calc(100% - ${v.heroCursorPct} + 12px);top:${v.heroClaimTop};transform:translateY(-50%);font:400 10.5px/1.2 'IBM Plex Mono',monospace;letter-spacing:.06em;text-transform:uppercase;color:#FDBA8C;white-space:nowrap">Claimed, not caused</span>
<span style="position:absolute;right:calc(100% - ${v.heroCursorPct} + 12px);top:${v.heroCausedTop};transform:translateY(-50%);font:400 10.5px/1.2 'IBM Plex Mono',monospace;letter-spacing:.06em;text-transform:uppercase;color:#EFF2F3;white-space:nowrap">Caused</span>
` : ''}
</div>
<ul style="list-style:none;margin:0;padding:12px 16px;display:flex;flex-wrap:wrap;gap:8px 20px;font:400 11px/1.4 'IBM Plex Mono',monospace;letter-spacing:.04em;color:rgba(239,242,243,.72)">
<li style="display:flex;align-items:center;gap:8px"><i style="width:16px;height:2px;background:#F97316"></i>Platform-reported</li>
<li style="display:flex;align-items:center;gap:8px"><i style="width:16px;height:2px;background:#EFF2F3"></i>Measured, test markets</li>
<li style="display:flex;align-items:center;gap:8px"><i style="width:16px;height:0;border-top:1.5px dashed rgba(239,242,243,.7)"></i>Control, holdout markets</li>
</ul>
<div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));border-top:1px solid rgba(239,242,243,.16)">
<div style="display:flex;flex-direction:column;gap:6px;padding:16px;border-right:1px solid rgba(239,242,243,.16)">
<span style="font:400 11px/1.4 'IBM Plex Mono',monospace;letter-spacing:.12em;text-transform:uppercase;color:rgba(239,242,243,.7)">Platform claimed</span>
<span data-k="readout.reported_roas_fmt" style="font:500 clamp(30px,3.4vw,42px)/1 Archivo,Helvetica,sans-serif;letter-spacing:-.02em;color:#F97316;font-variant-numeric:tabular-nums">3.4x</span>
<span style="font:400 12px/1.4 'IBM Plex Sans',sans-serif;color:rgba(239,242,243,.7)">ROAS, in-platform</span>
</div>
<div style="display:flex;flex-direction:column;gap:6px;padding:16px">
<span style="font:400 11px/1.4 'IBM Plex Mono',monospace;letter-spacing:.12em;text-transform:uppercase;color:rgba(239,242,243,.7)">Test measured</span>
<span id="hero-roi" style="font:500 clamp(30px,3.4vw,42px)/1 Archivo,Helvetica,sans-serif;letter-spacing:-.02em;color:#EFF2F3;font-variant-numeric:tabular-nums">${v.heroRoiFmt}</span>
<span style="font:400 12px/1.4 'IBM Plex Sans',sans-serif;color:rgba(239,242,243,.7)">Incremental ROAS, so far</span>
</div>
</div>
<div style="display:flex;flex-direction:column;gap:10px;padding:14px 16px 16px;border-top:1px solid rgba(239,242,243,.16)">
<div style="display:flex;justify-content:space-between;gap:12px;font:400 11px/1.4 'IBM Plex Mono',monospace;letter-spacing:.1em;text-transform:uppercase;color:rgba(239,242,243,.7)">
<span>90% interval · <span style="color:#EFF2F3;font-variant-numeric:tabular-nums">${v.heroCiFmt}</span></span>
<span style="display:flex;align-items:center;gap:8px;color:#EFF2F3"><span style="width:7px;height:7px;background:${v.heroSigSq}"></span>${v.heroSigLabel}</span>
</div>
<div style="position:relative;height:14px">
<div style="position:absolute;left:0;right:0;top:6px;height:1px;background:rgba(239,242,243,.25)"></div>
<div style="position:absolute;top:2px;height:9px;left:${v.heroCiLeft};width:${v.heroCiWidth};background:rgba(239,242,243,.28)"></div>
<div style="position:absolute;top:0;height:14px;width:2px;margin-left:-1px;left:${v.heroRoiLeft};background:#EFF2F3"></div>
<div style="position:absolute;top:0;height:14px;width:2px;margin-left:-1px;left:85%;background:#F97316"></div>
<div style="position:absolute;top:0;height:14px;width:1px;left:25%;background:rgba(239,242,243,.45)"></div>
</div>
<div style="position:relative;height:12px;font:400 10px/1 'IBM Plex Mono',monospace;color:rgba(239,242,243,.6)">
<span style="position:absolute;left:0">0x</span><span style="position:absolute;left:25%;transform:translateX(-50%)">1x</span><span style="position:absolute;left:50%;transform:translateX(-50%)">2x</span><span style="position:absolute;left:75%;transform:translateX(-50%)">3x</span><span style="position:absolute;right:0">4x</span>
</div>
<div style="display:flex;justify-content:space-between;align-items:center;gap:12px;padding-top:4px">
<span style="font:400 12px/1.45 'IBM Plex Sans',sans-serif;color:rgba(239,242,243,.7)">The interval narrows as each day of sales comes in.</span>
<button data-on-click="${h(v.replayHero)}" style="flex:none;background:none;border:0;border-bottom:1px solid rgba(239,242,243,.35);padding:0 0 3px;cursor:pointer;font:400 11px/1.2 'IBM Plex Mono',monospace;letter-spacing:.1em;text-transform:uppercase;color:rgba(239,242,243,.8)" class="hv3">Replay</button>
</div>
</div>
</figure>`
};
